### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by justushache** [TheAomx/HP-625-Linux-Fancontrol#2]
Im Sorry that i have to write again but it seems like the fancontrol service is not working properly. Ervery time I start the FanControl it prints in the Terminal:

 sudo /opt/FanControl
sh: 1: acpi: not found
terminate called after throwing an instance of 'std::runtime_error'
  what():  fgets failed
Aborted

and an Window with an crash report is opening
the windows says "FanControl crashed with SIGBRT in std::terminate()"
i am using Ubuntu 18.04 and under Unreportable Reason stands the text: "This package not seems to be installed correctly"

i would be very thankful if you would fix these crashes 
PS: in case you dont want to make any updates or something like this i could help developing the FanControl service 

sincerely Justus

**Comment by justushache** [comment]
interestingly this error only occurs if i put the laptop to sleep mode but when i restart it it is working properly.
So this isn't an very big issue, but i would be interested in why it crashes one time but the other not.

and is it posible to change the fan curve (i would do it myself in the source code but i dont now which lines do what)

**Comment by TheAomx** [comment]
Hi,
on the sleep mode problem: what happens if you try to run the following command in a terminal after using the sleep mode:

> sudo acpi -t | grep 'Thermal 0'| grep -oEe [0-9]+\.[0-9]

Does it work? It should print the current temperature of your cpu. If this does not work, the problem is that somehow acpi does not work after sleep mode. I use this command to get the current temperature of the cpu in the program.

Maybe you can print (if working) the complete output of acpi -t, because maybe the thermal device is not 0 in your case. I use another setup (ArchLinux with Linux Kernel 4.17 at the moment. You maybe have to change small parts in the program in order to work with ubuntu 18.04 properly! 

You can adjust the fan curve yourself. Look at main.cpp at lines 41-55. There the fan ids from /sys/devices/virtual/thermal/cooling_device* are listed and then thermal_areas are defined. You can change these areas to your personal preference.

**Comment by justushache** [comment]
The comment don't work when the laptop was in sleep mode but it looks like it won't work at all
Every time I try to run the comment it says: "sudo: acpi: command not found"

**Comment by TheAomx** [comment]
Ok, if the acpi command in general does not work for you, there is a general problem with your notebook.

Can you run other commands other than acpi? Without the acpi it is difficult to determine the current temperature of the CPU. You should maybe search on Google why acpi does not work after the laptop was in sleep mode. I never had a problem like that!

**Comment by justushache** [comment]
That you for your quick feedback it turned out that acpi was not installed
